language: ruby
rvm:
  - 2.4.2
services:
  - postgresql
before_install:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database gorails_test;' -U postgres
script:
  - export RAILS_ENV=test
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rspec
after_success:
  - coveralls
