development:
  cloud_name:  <%= ENV["CLOUD_NAME"] %>
  api_key:  <%= ENV["CLOUD_NAME"] %>
  api_secret:  <%= ENV["API_SECRET_CLOUD"] %>

production:
  cloud_name:  <%= ENV["CLOUD_NAME"] %>
  api_key:  <%= ENV["CLOUD_NAME"] %>
  api_secret:  <%= ENV["API_SECRET_CLOUD"] %>