default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  username: root
  password: PHVgah76465

development:
  <<: *default
  database: gorails

test:
  <<: *default
  database: gorails_test

production:
  <<: *default
  host:     postgres84167-gorails.jelasticlw.com.br
  database: gorails
  username: root
  password: PHVgah76465
